In [1]:
import torch

In [2]:
num_envs = 10

In [3]:
env_ids = torch.arange(0,num_envs)

In [4]:
pose_command_o = torch.zeros(num_envs, 7)

In [5]:
pos_x = (-1,1)
pos_y = (-0.6,0.6)
pos_z = (-0.4,0.4)

In [6]:
roll = (0, torch.pi / 12)
pitch = (0, torch.pi / 12)
yaw = (-torch.pi / 2, torch.pi / 2)

In [7]:
r = torch.empty(len(env_ids))
pose_command_o[env_ids, 0] = r.uniform_(*pos_x)
pose_command_o[env_ids, 1] = r.uniform_(*pos_y)
pose_command_o[env_ids, 2] = r.uniform_(*pos_z)

# -- orientation
euler_angles = torch.zeros_like(pose_command_o[env_ids, :3])
euler_angles[:, 0].uniform_(*roll)
euler_angles[:, 1].uniform_(*pitch)
euler_angles[:, 2].uniform_(*yaw)

# euler_angles[:, 0] = euler_angles[:, 0]
# euler_angles[:, 1] = euler_angles[:, 1]

tensor([-1.0604,  1.5451, -1.0663, -0.6307, -1.3155, -0.6864,  1.4137, -0.8215,
        -1.1015, -1.2362])

In [8]:
mask = torch.rand((num_envs,1))
mask

tensor([[0.8766],
        [0.6065],
        [0.7570],
        [0.3933],
        [0.9361],
        [0.5886],
        [0.0392],
        [0.3356],
        [0.6899],
        [0.8194]])

In [9]:
roll_idx = torch.where(mask >= 0.5)[0]
roll_idx

tensor([0, 1, 2, 4, 5, 8, 9])

In [10]:
pitch_idx = torch.where(mask < 0.5)[0]
pitch_idx

tensor([3, 6, 7])

In [11]:
euler_angles

tensor([[ 0.0235,  0.1663, -1.0604],
        [ 0.0948,  0.1848,  1.5451],
        [ 0.2563,  0.0056, -1.0663],
        [ 0.0877,  0.2282, -0.6307],
        [ 0.1153,  0.2265, -1.3155],
        [ 0.2085,  0.0575, -0.6864],
        [ 0.0504,  0.1531,  1.4137],
        [ 0.1930,  0.2091, -0.8215],
        [ 0.0794,  0.1306, -1.1015],
        [ 0.0568,  0.2129, -1.2362]])

In [12]:
euler_angles[pitch_idx, 0] = 0.0
euler_angles[roll_idx, 1] = 0.0

In [13]:
euler_angles

tensor([[ 0.0235,  0.0000, -1.0604],
        [ 0.0948,  0.0000,  1.5451],
        [ 0.2563,  0.0000, -1.0663],
        [ 0.0000,  0.2282, -0.6307],
        [ 0.1153,  0.0000, -1.3155],
        [ 0.2085,  0.0000, -0.6864],
        [ 0.0000,  0.1531,  1.4137],
        [ 0.0000,  0.2091, -0.8215],
        [ 0.0794,  0.0000, -1.1015],
        [ 0.0568,  0.0000, -1.2362]])

In [14]:
mask_sign = torch.rand((num_envs,1))
mask

tensor([[0.8766],
        [0.6065],
        [0.7570],
        [0.3933],
        [0.9361],
        [0.5886],
        [0.0392],
        [0.3356],
        [0.6899],
        [0.8194]])

In [21]:
pitch_sign = torch.sign(pose_command_o[pitch_idx, 0]) * -1
pitch_sign

tensor([ 1.,  1., -1.])

In [22]:
roll_sign = torch.sign(pose_command_o[roll_idx, 1])
roll_sign

tensor([-1.,  1.,  1.,  1., -1.,  1., -1.])

In [68]:
euler_angles

tensor([[ 0.2432,  0.0000,  0.5716],
        [ 0.0000,  0.0544,  1.2354],
        [ 0.1655,  0.0000, -0.1502],
        [ 0.0000,  0.2520, -1.2499],
        [ 0.1857,  0.0000,  0.7775],
        [ 0.0000,  0.1412, -0.3817],
        [ 0.0000,  0.2387, -1.3126],
        [ 0.0671,  0.0000,  1.1770],
        [ 0.0000,  0.0171,  0.0444],
        [ 0.1076,  0.0000,  0.6697]])

In [23]:
euler_angles[pitch_idx, 1] *= pitch_sign
euler_angles[roll_idx, 0] *= roll_sign

In [24]:
euler_angles

tensor([[-0.0235,  0.0000, -1.0604],
        [ 0.0948,  0.0000,  1.5451],
        [ 0.2563,  0.0000, -1.0663],
        [ 0.0000,  0.2282, -0.6307],
        [ 0.1153,  0.0000, -1.3155],
        [-0.2085,  0.0000, -0.6864],
        [ 0.0000,  0.1531,  1.4137],
        [ 0.0000, -0.2091, -0.8215],
        [ 0.0794,  0.0000, -1.1015],
        [-0.0568,  0.0000, -1.2362]])