In [3]:
import torch 
import numpy as np

In [4]:
def cart2sph(x, y, z):
    hxy = np.hypot(x, y)
    r = np.hypot(hxy, z)
    el = np.arctan2(z, hxy)
    az = np.arctan2(y, x)
    return az, el, r

In [5]:
def sph2cart(az, el, r):
    rcos_theta = r * np.cos(el)
    x = rcos_theta * np.cos(az)
    y = rcos_theta * np.sin(az)
    z = r * np.sin(el)
    return x, y, z

In [6]:
def torch_cart2sph(pos):
    # Extract x, y, z components
    x = pos[:, 0]
    y = pos[:, 1]
    z = pos[:, 2]

    # Compute spherical coordinates
    hxy = torch.hypot(x, y)
    r = torch.hypot(hxy, z)
    el = torch.atan2(z, hxy)
    az = torch.atan2(y, x)

    # Concatenate azimuth, elevation, and radius
    spherical = torch.stack((az, el, r), dim=1)

    return spherical

In [7]:
def torch_sph2cart(pos):
    # Extract az, el, r components
    az = pos[:, 0]
    el = pos[:, 1]
    r = pos[:, 2]

    rcos_theta = r * torch.cos(el)
    x = rcos_theta * torch.cos(az)
    y = rcos_theta * torch.sin(az)
    z = r * torch.sin(el)

    # Concatenate x, y, and z
    cartesian = torch.stack((x, y, z), dim=1)

    return cartesian

In [8]:
print(cart2sph(1,1,1))
print(cart2sph(1,1,0))
print(cart2sph(-1,-1,0))

(0.7853981633974483, 0.6154797086703873, 1.7320508075688774)
(0.7853981633974483, 0.0, 1.4142135623730951)
(-2.356194490192345, 0.0, 1.4142135623730951)


In [9]:
print(sph2cart(0.7854,0.6155,1.7321))

(1.0000122158831561, 1.0000158891398772, 1.000057098146021)


In [23]:
pos = torch.tensor([[1.0,1,1],[1.0,1,0],[-1.0,-1,0]])

In [24]:
cart2sph(pos[...,0],pos[...,1],pos[...,2])

(tensor([ 0.7854,  0.7854, -2.3562]),
 tensor([0.6155, 0.0000, 0.0000]),
 tensor([1.7321, 1.4142, 1.4142]))

In [28]:
torch_cart2sph(pos)

tensor([[ 0.7854,  0.6155,  1.7321],
        [ 0.7854,  0.0000,  1.4142],
        [-2.3562,  0.0000,  1.4142]])

In [13]:
torch_sph2cart(torch.tensor([[ 0.7854,  0.6155,  1.7321]]))

tensor([[1.0000, 1.0000, 1.0001]])